paulsohn/autoware_launch:
  default-upstream-id: awf
  upstreams:
    awf: # upstream ID
      name: AWF
      url: https://github.com/autowarefoundation/autoware_launch.git
      syncs:
        - upstream: main
          base: main
          reviewers: # use actual GitHub users or teams
            - paulsohn
