<?xml version="1.0"?>
<package format="3">
  <name>autoware_launch_config</name>
  <version>0.50.0</version>
  <description>Configuration files for autoware_launch package</description>

  <maintainer email="yukihiro.saito@tier4.jp">Yukihiro Saito</maintainer>
  <maintainer email="ryohsuke.mitsudome@tier4.jp">Ryohsuke Mitsudome</maintainer>
  <maintainer email="mfc@leodrive.ai">M. Fatih Cırıt</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <autoware_guideline_check file="test/autoware_guideline_check.yaml"/>
  </export>
</package>
